### PR TITLE
Add implementation for disconnect callback

### LINKED ISSUE #7: onDisconnect not defined
Just forgot to add:
`
void MQTTClient::onDisconnect(THandlerFunction fn)
{
    _disconnected_cb = fn;
}
`
in file ESP8266MQTTClient.cpp

### PR DESCRIPTION
**Pull request by cakesifu**
fixes #7

### CODE REVIEW

**Comment by cakesifu** [comment]
Do you think you could merge this in @tuanpmt ? It would be really great to have the onDisconnect feature.

**Comment by tuanpmt** [comment]
i forgot it
Thanks.,

**Comment by cakesifu** [comment]
Thank you for merging. Could we release this as `1.0.5`?

**Comment by tuanpmt** [comment]
Done @cakesifu

**Pull request merged**
